import React from "react";
import type { Metadata } from "next";
import "./globals.css";
import StyledComponentsRegistry from "@/lib/AntdRegistry";
import { Toaster } from "react-hot-toast";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        {/* google fonts */}
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Inter:wght@100;200;300;400;500;600;700;800;900&display=swap"
          rel="stylesheet"
        ></link>
      </head>
      <body>
        <Toaster
          position="top-center"
          toastOptions={{
            success: {
              style: {
                background: "#FFFFFF",
                border: "2px solid #0444BD",
                color: "#000000",
              },
            },
            error: {
              style: {
                background: "#FFCCCC",
                border: "2px solid #FF0000",
                color: "#000000",
              },
            },
            style: {
              background: "#FFFFFF",
              border: "2px solid #0444BD",
              color: "#333",
            },
          }}
        />
        <StyledComponentsRegistry>{children}</StyledComponentsRegistry>
      </body>
    </html>
  );
}
